[project]
name = "cognee-community-vector-adapter-pinecone"
version = "0.0.1"
description = "Pinecone vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "pinecone>=3.0.0",
    "cognee>=0.2.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/.venv",
]
